/**
 * data.js — LEGO Modular Building definitions
 *
 * Each entry describes one modular. The `id` must match the folder name
 * under /models/ (e.g. "cafe-corner" → /models/cafe-corner/cafe-corner.gltf).
 *
 * Fields
 * ──────
 * id         string   Slug — must match the model folder and file name
 * name       string   Display name
 * year       number   Release year
 * set        string   LEGO set number
 * floors     number   Number of floors (drives scale + floor-clip control)
 * widthU     number   Width in 32-stud modules (1 for most, 2 for wide sets)
 * color      string   Fallback hex colour shown before thumbnail loads
 * accent     string   Accent / trim hex (placeholder geometry only)
 * roofColor  string   Roof / parapet hex (placeholder geometry only)
 */
const MODULARS = [
  {
    id: 'cafe-corner',
    name: 'Café Corner',
    year: 2007,
    set: '10182',
    floors: 4,
    widthU: 1,
    category: 'official',
    color: '#ffffff', accent: '#e8b86d', roofColor: '#8b6635',
  },
  {
    id: 'market-street',
    name: 'Market Street',
    year: 2007,
    set: '10190',
    floors: 4,
    widthU: 1,
    category: 'official',
    color: '#ffffff', accent: '#e0c090', roofColor: '#806040',
  },
  {
    id: 'green-grocer',
    name: 'Green Grocer',
    year: 2008,
    set: '10185',
    floors: 4,
    widthU: 1,
    category: 'official',
    color: '#ffffff', accent: '#7db860', roofColor: '#3d6030',
  },
  {
    id: 'fire-brigade',
    name: 'Fire Brigade',
    year: 2011,
    set: '10197',
    floors: 4,
    widthU: 1,
    scaleOverride: 0.01707,
    category: 'official',
    color: '#ffffff', accent: '#e05040', roofColor: '#8c2020',
  },
  {
    id: 'grand-emporium',
    name: 'Grand Emporium',
    year: 2010,
    set: '10211',
    floors: 4,
    widthU: 1,
    scaleOverride: 0.01707,
    category: 'official',
    color: '#ffffff', accent: '#d4c8a8', roofColor: '#a89870',
  },
  {
    id: 'pet-shop',
    name: 'Pet Shop',
    year: 2011,
    set: '10218',
    floors: 4,
    widthU: 1,
    category: 'official',
    color: '#ffffff', accent: '#d4aa78', roofColor: '#806040',
  },
  {
    id: 'town-hall',
    name: 'Town Hall',
    year: 2012,
    set: '10224',
    floors: 4,
    widthU: 1,
    category: 'official',
    color: '#ffffff', accent: '#d4c8a0', roofColor: '#707060',
  },
  {
    id: 'palace-cinema',
    name: 'Palace Cinema',
    year: 2013,
    set: '10232',
    floors: 4,
    widthU: 1,
    category: 'official',
    color: '#ffffff', accent: '#e8d4a0', roofColor: '#c8b880',
  },
  {
    id: 'parisian-restaurant',
    name: 'Parisian Restaurant',
    year: 2014,
    set: '10243',
    floors: 4,
    widthU: 1,
    category: 'official',
    color: '#ffffff', accent: '#d8cca8', roofColor: '#888070',
  },
  {
    id: 'detective-office',
    name: "Detective's Office",
    year: 2015,
    set: '10246',
    floors: 4,
    widthU: 1,
    category: 'official',
    color: '#ffffff', accent: '#8898b8', roofColor: '#404e60',
  },
  {
    id: 'brick-bank',
    name: 'Brick Bank',
    year: 2016,
    set: '10251',
    floors: 4,
    widthU: 1,
    scaleOverride: 0.01707,
    category: 'official',
    color: '#ffffff', accent: '#d4c898', roofColor: '#908060',
  },
  {
    id: 'assembly-square',
    name: 'Assembly Square',
    year: 2017,
    set: '10255',
    floors: 4,
    widthU: 1.5,
    category: 'official',
    color: '#ffffff', accent: '#d4a840', roofColor: '#806020',
  },
  {
    id: 'downtown-diner',
    name: 'Downtown Diner',
    year: 2018,
    set: '10260',
    floors: 4,
    widthU: 1,
    scaleOverride: 0.01707,
    category: 'official',
    color: '#ffffff', accent: '#f0d860', roofColor: '#a08820',
  },
  {
    id: 'corner-garage',
    name: 'Corner Garage',
    year: 2019,
    set: '10264',
    floors: 4,
    widthU: 1,
    category: 'official',
    color: '#ffffff', accent: '#b0a888', roofColor: '#686050',
  },
  {
    id: 'bookshop',
    name: 'Bookshop',
    year: 2020,
    set: '10270',
    floors: 4,
    widthU: 1,
    category: 'official',
    color: '#ffffff', accent: '#c08858', roofColor: '#704828',
  },
  {
    id: 'police-station',
    name: 'Police Station',
    year: 2021,
    set: '10278',
    floors: 4,
    widthU: 1,
    category: 'official',
    color: '#ffffff', accent: '#c0b8a0', roofColor: '#606858',
  },
  {
    id: 'boutique-hotel',
    name: 'Boutique Hotel',
    year: 2022,
    set: '10297',
    floors: 4,
    widthU: 1,
    category: 'official',
    color: '#ffffff', accent: '#d0b8e0', roofColor: '#785888',
  },
  {
    id: 'jazz-club',
    name: 'Jazz Club',
    year: 2023,
    set: '10312',
    floors: 4,
    widthU: 1,
    category: 'official',
    color: '#ffffff', accent: '#506070', roofColor: '#202830',
  },
  {
    id: 'natural-history-museum',
    name: 'Natural History Museum',
    year: 2024,
    set: '10326',
    floors: 4,
    widthU: 1.5,
    category: 'official',
    color: '#ffffff', accent: '#d0c8b0', roofColor: '#a09080',
  },
  {
    id: 'tudor-corner',
    name: 'Tudor Corner',
    year: 2025,
    set: '10350',
    floors: 4,
    widthU: 1,
    category: 'official',
    color: '#ffffff', accent: '#d4c0a0', roofColor: '#503820',
  },
  {
    id: 'spring-lantern-festival',
    name: 'Spring Lantern Festival',
    year: 2021,
    set: '80107',
    floors: 1,
    widthU: 1.5,
    scaleOverride: 0.01707,
    category: 'unofficial',
    color: '#ffffff', accent: '#d4c0a0', roofColor: '#503820',
  },
  {
    id: 'daily-bugle',
    name: 'Daily Bugle',
    year: 2021,
    set: '76178',
    floors: 5,
    widthU: 1,
    scaleOverride: 0.01707,
    category: 'unofficial',
    color: '#ffffff', accent: '#d4c0a0', roofColor: '#503820',
  },
  {
    id: 'modular-lego-store',
    name: 'Modular LEGO Store',
    year: 2022,
    set: '910009',
    floors: 2,
    widthU: 1,
    scaleOverride: 0.01707,
    category: 'unofficial',
    color: '#ffffff', accent: '#d4c0a0', roofColor: '#503820',
  },
  {
    id: 'sanctum-sanctorum',
    name: 'Sanctum Sanctorum',
    year: 2022,
    set: '76218',
    floors: 4,
    widthU: 1,
    scaleOverride: 0.01707,
    category: 'unofficial',
    color: '#ffffff', accent: '#d4c0a0', roofColor: '#503820',
  },
  {
    id: 'venetian-houses',
    name: 'Venetian Houses',
    year: 2022,
    set: '910023',
    floors: 3,
    widthU: 2,
    scaleOverride: 0.01707,
    category: 'unofficial',
    color: '#ffffff', accent: '#d4c0a0', roofColor: '#503820',
  },
  {
    id: 'retro-bowling-alley',
    name: 'Retro Bowling Alley',
    year: 2022,
    set: '910013',
    floors: 1,
    widthU: 2,
    scaleOverride: 0.01707,
    category: 'unofficial',
    color: '#ffffff', accent: '#d4c0a0', roofColor: '#503820',
  },
  {
    id: 'avengers-tower',
    name: 'Avengers Tower',
    year: 2023,
    set: '76269',
    floors: 6,
    widthU: 1,
    category: 'unofficial',
    color: '#ffffff', accent: '#d4c0a0', roofColor: '#503820',
  },
  {
    id: 'modular-construction-site',
    name: 'Modular Construction Site',
    year: 2023,
    set: '910008',
    floors: 4,
    widthU: 1,
    category: 'unofficial',
    color: '#ffffff', accent: '#d4c0a0', roofColor: '#503820',
  },
  {
    id: 'brick-cross-train-station',
    name: 'Brick Cross',
    year: 2024,
    set: '910034',
    floors: 2,
    widthU: 1.5,
    category: 'unofficial',
    color: '#ffffff', accent: '#d4c0a0', roofColor: '#503820',
  },
  {
    id: 'botanical-garden',
    name: 'Botanical Garden',
    year: 2024,
    set: '21353',
    floors: 2,
    widthU: 2,
    category: 'unofficial',
    color: '#ffffff', accent: '#d4c0a0', roofColor: '#503820',
  },
  {
    id: 'x-mansion',
    name: 'X-Men: The X-Mansion',
    year: 2024,
    set: '79294',
    floors: 3,
    widthU: 2,
    category: 'unofficial',
    color: '#ffffff', accent: '#d4c0a0', roofColor: '#503820',
  },
  {
    id: 'arkham-asylum',
    name: 'Arkham Asylum',
    year: 2025,
    set: '76300',
    floors: 3,
    widthU: 1,
    category: 'unofficial',
    color: '#ffffff', accent: '#d4c0a0', roofColor: '#503820',
  },
  {
    id: 'straight-road',
    name: 'Straight Road',
    year: 2005,
    set: '7280',
    floors: 1,
    widthU: 1,
    scaleOverride: 0.01707,
    category: 'road',
    color: '#ffffff', accent: '#d4c0a0', roofColor: '#503820',
  },
  {
    id: 'cross-road',
    name: 'Cross Road',
    year: 2005,
    set: '7280',
    floors: 1,
    widthU: 1,
    scaleOverride: 0.01707,
    category: 'road',
    color: '#ffffff', accent: '#d4c0a0', roofColor: '#503820',
  },
  {
    id: 'curved-road',
    name: 'Curved Road',
    year: 2005,
    set: '7281',
    floors: 1,
    widthU: 1,
    scaleOverride: 0.01707,
    category: 'road',
    color: '#ffffff', accent: '#d4c0a0', roofColor: '#503820',
  },
  {
    id: 't-road',
    name: 'T Road',
    year: 2005,
    set: '7281',
    floors: 1,
    widthU: 1,
    scaleOverride: 0.01707,
    category: 'road',
    color: '#ffffff', accent: '#d4c0a0', roofColor: '#503820',
  },
];